### PR TITLE
popup window

### PR DESCRIPTION
**Pull request by ijosue16**
in this branch I added a popup window

### CODE REVIEW

**Review by fobadara — CHANGES_REQUESTED** [review]
Hi @ijosue16, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linters are passing
✅ Project looks professionl

## Required Changes ♻️
_Check the comments under the review._
I had to include the comments here instead of inline because I can't access the files in question.

[REQUIRED] Kindly make the image in the pop for the desktop screen centred without extra spaces on the side. And kindly ensure that the image and texts below the image start from the same point on the left side.

[REQUIRED] Kindly remove the empty java.js file since it does nothing
[REQUIRED] This is all you need in the array that we are dynamically creating the pop up from:
```
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```
Then you can create the elements with `array.map`. In future when you want to add another project all you need to do is add another object.

|Template|Your design|
|---------|------------|
|image|image|

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- following the best practices for commit messages like using the imperative form like Created_sidebar or sidebar

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ijosue16** [comment]
@fobadara please I think it is not  a required feature to have only those elements in our array of object in the project and also could you please explain what you mean

**Comment by ijosue16** [comment]
> @fobadara please I think it is not a required feature to have only those elements in our array of objects in the project.

And as proof, these are the guidelines they gave us saying that the array is not limited to that certain value you have told me as you can see below they said minimum not maximum.


Capture

**Review by Kossi-stack — APPROVED** [review]
## Status: Approved ✔️
**Hi @ijosue16,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉


You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Pull request merged**
